### ISSUE TITLE
[Bug]: include react-helmet-async in dependencies

### ISSUE THREAD

**Issue by dberardo-com** [Py4Js/pyscript-react#1252]
### What happened?

the library does not define react-helmet-async in its (peer) dependencies block.

this is needed for it to work after installation 

### Version

0.0.2

### How to reproduce?

Click chrome.exe

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dberardo-com** [comment]
also: is it possible to customize the ugly pyscript loader ?

**Comment by KrzysztofZawisla** [comment]
Hi, `react-helmet-async ` is already declared in peer dependencies as optional. It's done like that because not everyone would like to attach pyscript by a provider. `PyScriptLoader` part will have forwardRef in the future, so it will be possible by the next library update to style the tag by for example emotion or styled-components.

**Comment by KrzysztofZawisla** [comment]
@dberardo-com I just released version 0.0.4 with forwardRef on every component that isn't a provider. From my side, everything that I can do about styling is done.
